// <auto-generated />
using System;
using DependencyInjection.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DependencyInjection.EfCoreUserManagement.Migrations
{
    [DbContext(typeof(DependencyInjectionDbContext))]
    [Migration("20221115123221_ChangePKforUsers")]
    partial class ChangePKforUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DependencyInjection.Entities.Users.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("4f656c72-cb86-4009-b42e-3a921a22896f"),
                            BirthDate = new DateTime(2000, 12, 5, 9, 52, 21, 252, DateTimeKind.Local).AddTicks(595),
                            Email = "Caroline.Little4@yahoo.com",
                            FirstName = "Caroline",
                            LastName = "Little"
                        },
                        new
                        {
                            UserId = new Guid("a4db41de-b0c2-4d13-98bb-cee92ed26745"),
                            BirthDate = new DateTime(1982, 3, 16, 6, 23, 6, 291, DateTimeKind.Local).AddTicks(8780),
                            Email = "Judy92@yahoo.com",
                            FirstName = "Judy",
                            LastName = "Walter"
                        },
                        new
                        {
                            UserId = new Guid("338859fd-ac5c-43cc-88c4-132a25211a42"),
                            BirthDate = new DateTime(1990, 8, 28, 22, 15, 36, 536, DateTimeKind.Local).AddTicks(2425),
                            Email = "Sammy32@gmail.com",
                            FirstName = "Paulette",
                            LastName = "Beahan"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
